try:
    raise Exception('ssss')
except Exception as error:
    print(error)